// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGConstants
{
        public const string achievement_tomato = "CgkIh9b_1uACEAIQEw"; // <GPGSID>
        public const string achievement_hammer = "CgkIh9b_1uACEAIQCQ"; // <GPGSID>
        public const string achievement_cactus = "CgkIh9b_1uACEAIQBQ"; // <GPGSID>
        public const string achievement_grenade = "CgkIh9b_1uACEAIQCA"; // <GPGSID>
        public const string achievement_banana = "CgkIh9b_1uACEAIQAg"; // <GPGSID>
        public const string achievement_icecream = "CgkIh9b_1uACEAIQCg"; // <GPGSID>
        public const string achievement_tennis = "CgkIh9b_1uACEAIQEQ"; // <GPGSID>
        public const string achievement_pookachu = "CgkIh9b_1uACEAIQDA"; // <GPGSID>
        public const string achievement_beach_ball = "CgkIh9b_1uACEAIQAw"; // <GPGSID>
        public const string achievement_football_ball = "CgkIh9b_1uACEAIQBw"; // <GPGSID>
        public const string achievement_sneaker = "CgkIh9b_1uACEAIQEA"; // <GPGSID>
        public const string achievement_boomerang = "CgkIh9b_1uACEAIQBA"; // <GPGSID>
        public const string achievement_pookeball = "CgkIh9b_1uACEAIQDQ"; // <GPGSID>
        public const string achievement_toilet_paper = "CgkIh9b_1uACEAIQEg"; // <GPGSID>
        public const string achievement_flowerpot = "CgkIh9b_1uACEAIQBg"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIh9b_1uACEAIQAQ"; // <GPGSID>
        public const string achievement_light_beer_bottle = "CgkIh9b_1uACEAIQCw"; // <GPGSID>
        public const string achievement_premium_beer_bottle = "CgkIh9b_1uACEAIQDg"; // <GPGSID>
        public const string achievement_rugby_ball = "CgkIh9b_1uACEAIQDw"; // <GPGSID>

}

